baseurl = "https://sagiadinos.com"
title = "sagiadinos"
theme = "hugo-theme-stack"
languagecode = "en"
defaultcontentlanguage = "en"



[[menus.main]]
name = "Articles"
url = "/articles/"
weight = 1

[[menus.main]]
name = "About"
url = "/about/"
weight = 2

[pagination]
pagerSize = 20


[params.footer]
since = 2026

[params]
mainSections = ["articles"]
description = "Niko Sagiadinos - Developer of GarlicSignage. Open source digital signage without vendor lock-in."
keywords = "digital signage, SMIL, open source, GarlicSignage"
customCSS = ["scss/custom.scss"]

[params.sidebar]
avatar = "images/sagiadinos.jpg"
subtitle = "Open Source Digital Signage. No lock-in. No bullshit"

[params.article]
toc = true
readingTime = true

[params.colorScheme]
toggle = true
default = "auto"

[[params.widgets.page]]
type = "toc"

[[menus.social]]
name = "GitHub"
url = "https://github.com/sagiadinos/"
weight = 1
params = { icon = "brand-github" }

[[menus.social]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/niko-sagiadinos/"
weight = 2
params = { icon = "brand-linkedin" }

[[menus.social]]
name = "GarlicSignage"
url = "https://garlic-signage.com"
weight = 3
params = { icon = "world-www" }